config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  
=======
>>>>>>> upstream/master
  root "posts#index"

  resources :posts
  resources :users

<<<<<<< HEAD
  namespace :admin do 
    resources :posts
    resources :users
    resources :categories
    root to: "posts#index"
  end
  
  get '/user/login', to: 'users#login'
=======
>>>>>>> upstream/master
  get '/user/login', to: 'users#login'
  post '/user/login', to: 'users#login'
  get '/user/logout', to: 'users#logout'
  post '/users/new', to: 'users#create'
<<<<<<< HEAD
  post '/users/:id', to: 'users#topup'
=======
>>>>>>> upstream/master

  post 'posts/:id', to: 'bills#create'

  get 'posts/ajax/category_selection', to: 'posts#category_selection'
  get 'posts/ajax/province_selection', to: 'posts#province_selection'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :posts
	has_many :bills
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
     @user = User.find(params[:id])
     @posts = Post.where(user_id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      @user[:role] = 'visitor'
      @user[:coin] = '0'
      if @user.save
        format.html { redirect_to root_path}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  def login
    if user = User.find_by(account:params[:account])
      if  user && user.authenticate(params[:password])
        # Save the user ID in the session so it can be used in
        session[:user_id] = user.id
        redirect_to root_path 
      else  flash.now[:danger] = 'sai tên đăng nhập hoặc mật khẩu!'
      end
    else
      if params[:account]
        flash.now[:danger] = 'sai tên đăng nhập hoặc mật khẩu!'
      end
      render :login
    end
  end

  def logout
    session[:user_id] = nil 
    redirect_to root_path
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :name, :password, :role, :coin)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
<<<<<<< HEAD
  before_action :set_user, only: %i[ show edit update destroy topup]
  skip_before_action :verify_authenticity_token , :only => [:topup]
=======
  before_action :set_user, only: %i[ show edit update destroy ]
>>>>>>> upstream/master

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
<<<<<<< HEAD
    @post_accepted = Post.where(user_id: params[:id], status: "đã duyệt")
    @post_pending = Post.where(user_id: params[:id], status: "chưa duyệt")
    @post_refused = Post.where(user_id: params[:id], status: "từ chối")
    @bill_rent = Bill.select('posts.*, bills.*').joins(:post).where(user_id: params[:id])
  end

  def topup
    bank = Bank.find_by(code: params[:code], seri: params[:seri])
    respond_to do |format| 
      unless bank.nil?
        if(bank.status == "valid")
          @user.coin += bank.price
          bank.status = "expire"
          bank.save
          @user.save
          format.html { redirect_to @user, success: "chúc mừng bạn đã nạp thành công "+bank.price.to_s+" vào tài khoản" }
        else 
          format.html { redirect_to @user, warning: "thẻ đã được sử dụng" }
        end
      else
        format.html { redirect_to @user, danger: "bạn đã nhập sai số seri hoặc mã thẻ" }
      end
    
    end

=======
     @user = User.find(params[:id])
     @posts = Post.where(user_id: params[:id])
>>>>>>> upstream/master
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
<<<<<<< HEAD

=======
>>>>>>> upstream/master
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      @user[:role] = 'visitor'
      @user[:coin] = '0'
      if @user.save
        format.html { redirect_to root_path}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  def login
    if user = User.find_by(account:params[:account])
      if  user && user.authenticate(params[:password])
        # Save the user ID in the session so it can be used in
        session[:user_id] = user.id
        redirect_to root_path 
      else  flash.now[:danger] = 'sai tên đăng nhập hoặc mật khẩu!'
      end
    else
      if params[:account]
        flash.now[:danger] = 'sai tên đăng nhập hoặc mật khẩu!'
      end
      render :login
    end
  end

  def logout
    session[:user_id] = nil 
    redirect_to root_path
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :name, :password, :role, :coin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= form_with(model: user, html:{class:'register-form',id:"register-form", name:"regis", onsubmit:"return checkRegis()",enctype:"multipart/form-data"})  do |form| %>
  <div class="form-group">
    <%= form.text_field :name,maxlength:"20",id:"name",placeholder:"Họ và tên"  %>
  </div>
  <div class="row">
  </div>
  <div class="form-group">
    <%= form.text_field :account,id:"account",placeholder:"Tên tài khoản" %>
  </div>
  <div class="form-group">
    <%= form.password_field :password,id:"passw",placeholder:"Mật khẩu" %>
  </div>
  <div class="form-group">
     <%= form.password_field :password_confirmation,id:"pass",placeholder:"Nhập lại mật khẩu" %>
  </div>
 <!--  <label for="frontID" style="width: 100%">
    <div class="form-group" id="frntid" style="width: 100%; height: 200px; border: 1px solid black;">
      <input type="file" name="frontID" id="frontID" style="display: none;" accept=".jpg,.jpeg,.png" />
      <img src="" id="ifid" for="frontID" style="display: none;">
      <label id="fid" for="frontID" >ảnh CMND mặt trước</label>
    </div>
  </label>
  <label for="backID" style="width: 100%">
   <div class="form-group" style="width: 100%; height: 200px; border: 1px solid black;">
    <input type="file" name="backID" id="backID" accept=".jpg,.jpeg,.png"  style="display: none;"/>
    <img src="" id="ibid" style="display: none;">
    <label id="bid" for="backID" >ảnh CMND mặt sau</label>
  </div>
</label> -->
<div class="form-group">
  <% if user.errors.any? %>
  <div id="error_explanation">
    <p style="color: red">Đăng ký thất bại:</p>
    <ul>
      <% user.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>    
  <% end %>
</div>
<div class="field">
</div>
<div class="form-group form-button">
  <%= form.submit "Đăng ký", :class=> "form-submit",  :id=> "signup", data: { disable_with: false } %>
</div>
<% end %>

app/views/users/_history.html.erb
<style type="text/css">
	.list-item tr{
		margin-bottom: 10px;
		border-bottom: 1px solid #DFE3ED;
	}
	.list-item td{
		padding: 5px !important;
		border: none !important;
	}
	.list-item th{
		padding: 5px !important;
		border: none !important;
	}
	td p{
		margin: 0 0 5px 35px;
		text-align: left;
	}
	.center{
		padding-top: 30px;
		margin: auto;
		width: 60%;
	}
	.status{
		border: 1px solid black;
		margin-top: 5px;
		cursor: pointer;
	}
	.description{
		width: 300px;
		height: 21px;
	    overflow: hidden;
	    white-space: nowrap; 
	    text-overflow: ellipsis;
	    margin-top: 5px;
	}
	.item{
		margin-right: 45px;
		padding: .6rem 0;
		color: #9B9B9B;
		cursor: pointer;
	}
	.item:hover{
		color: #212121;
	}
	.active{
		color: #212121;
		border-bottom: 3px solid #40a691;
	}
	.active > span{
		color: #40a691;
	}
	.nav{
		border-bottom: 1px solid #F2F5F8;
		margin-bottom: 20px;
	}
	.wrapp{
		font-size: 14px;
	}
	.column-title{
		text-align: center;
		background-color: #f2f5f8;

	}
</style>
<div class="box-area">
	<h3 class="title">lịch sử giao dịch</h3>
</div>
<div id="managerental">
	<% if @bill_rent.empty? %>
    <p style='margin-top:20px;'>bạn chưa thực hiện giao dịch nào.<p>
	<% else -%>
    <div class="row">
	    <table class="col-12 list-item" style="text-align: center;">	
	    	<tr class="column-title">
	    		<th>id</th>
	    		<th>thông tin giao dịch</th>
	    		<th>tổng tiền</th>
	    		<th>thời gian thuê</th>
	    	</tr>
		    <% @bill_rent.each do |bill| %>
	    	<tr>
	    		<td><%=bill.id%></td>
	    		<td><p><%=bill.title%></p><p><%=bill.price%>vnđ</p></td>
	    		<td><%=bill.amount%></td>
	    		<td><%=bill.rent_date%> - <%=bill.return_date%></td>
	    	</tr>
	    	<% end -%>
	    </table>
    </div>

	<% end -%>
 </div>

app/views/users/_infor.html.erb
	<style type="text/css">
		input{
			display: inline-block;
			padding: 6px 10px;
		}
	</style>
	<h3 style="text-align: center; margin-bottom: 20px; ">Thông tin cá nhân</h3>
	<div class="group">
		<label >Họ và tên:</label>
<<<<<<< HEAD
		<input style="width:50%" type="text" name="fullname" disabled value="<%= user.name %>">
=======
		<input style="width:50%" type="text" name="fullname" disabled value="<%= @user.name %>">
>>>>>>> upstream/master
	</div>


app/views/users/_manage.html.erb
<style type="text/css">
<<<<<<< HEAD
	.list-item td{
		text-align: left !important;
		padding: 5px !important;
		border: none !important;
	}
	.list-item tr{
		margin-bottom: 10px;
		border-bottom: 1px solid #DFE3ED;
	}
	td p{
		margin: 0 0 5px 5px;
=======
	td{
		padding: 10px;
		border: 1px solid black;
	}
	tr{
		margin-bottom: 10px;
>>>>>>> upstream/master
	}
	.center{
		padding-top: 30px;
		margin: auto;
		width: 60%;
	}
	.status{
		border: 1px solid black;
		margin-top: 5px;
		cursor: pointer;
	}
	.description{
		width: 300px;
		height: 21px;
	    overflow: hidden;
	    white-space: nowrap; 
	    text-overflow: ellipsis;
	    margin-top: 5px;
	}
<<<<<<< HEAD
	.item{
		margin-right: 45px;
		padding: .6rem 0;
		color: #9B9B9B;
		cursor: pointer;
	}
	.item:hover{
		color: #212121;
	}
	.active{
		color: #212121;
		border-bottom: 3px solid #40a691;
	}
	.active > span{
		color: #40a691;
	}
	.nav{
		border-bottom: 1px solid #F2F5F8;
		margin-bottom: 20px;
	}
	.wrapp{
		font-size: 14px;
	}
</style>
<div class="box-area">
	<h3 class="title">Quản lý tin đăng</h3>
</div>
<ul class="nav">
	<li class="item active" id="accepted" onclick="changeManage(this.id)">Tin đang rao <span><%=@post_accepted.size %></span></li>
	<li class="item" id="pending" onclick="changeManage(this.id)">Tin chờ duyệt <span><%=@post_pending.size %></span></li>
	<li class="item" id="refused" onclick="changeManage(this.id)">Tin bị từ chối <span><%=@post_refused.size %></span></li>
</ul>
<div id="managerental">
	<%= render 'posts' , posts: @post_accepted%>
 </div>
=======
</style>
<h3 style="text-align: center; margin-bottom: 20px;">Quản lý tin</h3>
<div id="managerental">
	<% if posts.empty? %>
    <p style='margin-top:20px;'>Bạn chưa đăng tin nào.<p>
	<% else -%>
    <div class="row">
	    <table class="col-12" style="text-align: center;">	
	    	<!-- <tr>
	    		<th>Ảnh</th>
	    		<th>TIêu đề</th>
	    		<th>Giá</th>
	    		<th></th>
	    		<th></th>
	    	</tr> -->
	    	<% posts.each do |post| %>
	    	<tr>
	    		<td style=" width: 100px; height: 60px;"><%= image_tag url_for(post.image),:style => "width: 100%; height: 100%" %></td>
	    		<td><%=post.title%></td>
	    		<td><%=post.price%></td>
	    		<td><%= link_to 'Sửa', edit_post_path(post.id)%></td>
	    		<td><%= link_to 'Xoá', post_path(post.id), :method => :delete, :confirm => 'Are you sure?' %></td>
	    	</tr>
	    	<% end -%>
	    </table>
    </div>
	<% end -%>
 </div>
>>>>>>> upstream/master

app/views/users/_posts.html.erb
<% if posts.empty? %>
    <p style='margin-top:20px;'>Không có tin nào ở đây.<p>
	<% else -%>
    <div class="row">
	    <table class="col-12 list-item" style="text-align: center;">	
		    	<% posts.each do |post| %>
	    	<tr>
	    		<td style=" width: 100px; height: 80px;"><%= image_tag url_for(post.image),:style => "width: 100%; height: 100%" %></td>
	    		<td><p><%=post.title%></p><p><%=post.price%></p></td>
	    		<td><%= link_to 'Sửa', edit_post_path(post.id)%></td>
	    		<td><%= link_to 'Xoá', post_path(post.id), :method => :delete, :confirm => 'Bạn có chắc là muốn xoá sản phẩm này?' %></td>
	    	</tr>
	    	<% end -%>
	    </table>
    </div>

	<% end -%>

app/views/users/_wallet.html.erb
<style type="text/css">
	.center{
		padding-top: 30px;
		margin: auto;
		width: 60%;
	}
	.group{
		margin-bottom: 10px;
	}
	.coin{
		border: 1px solid black;
		width: 80%;
		margin-bottom: 20px;
		margin-left: 50px;
		padding: 5px;
		text-align: center;
	}
	.vertical-line{
		border-left: 1px solid black;
		height: 250px;
		position: absolute;
		left: 50%;
		margin-left: -3px;
		top: 130px;
	}
	.title .top-up{
		display: inline-block;
		margin-left: 140px;
	}
	.title .top-up span{
		margin-right: 20px;
		color: #9B9B9B;
		cursor: pointer;
	}
	.title .top-up span.active{
		border-bottom: 2px solid green;
		color: black;
		cursor: default;
	}
</style>
<h3 style="text-align: center; margin-bottom: 20px;">Ví cá nhân</h3>
<div id="wllt" style="height: 323px">
	<p class="coin">số dư trong tài khoản: <%= user.coin %>vnđ </p>
	<div class="title" style="border-bottom: none">
		<h2 style="margin-bottom: 30px">Nạp tiền vào tài khoản:</h2>
		<div class="top-up">
			<span class="active" id="card" onclick="topUp(this.id)">Thẻ điện thoại</span>
			<span id="bank" onclick="topUp(this.id)">thẻ ngân hàng</span>
		</div>
	</div>
	<div class="row" id="topup">
		<table class="col-5" >
			<tr>
				<th>Mệnh giá</th>
				<th>Quy đổi</th>
			</tr>
			<tr>
				<td>20.000 vnđ</td>
				<td>phí 10%</td>
			</tr>
			<tr>
				<td>50.000 vnđ</td>
				<td>phí 10%</td>
			</tr>
			<tr>
				<td>100.000 vnđ</td>
				<td>phí 10%</td>
			</tr>
			<tr>
				<td>200.000 vnđ</td>
				<td>phí 10%</td>
			</tr>
		</table>
		<div class="col-1 "></div>
		<div class="vertical-line"></div>
		<form  method="POST" class="col-6"  style="padding-top: 0px">
			<div class="group">
				<label>Số seri:</label>
				<input type="text" name="seri" placeholder="số seri">
			</div>
			<div class="group">
				<label>Mã thẻ:</label>
				<input type="text" name="code" placeholder="mã thẻ">
			</div>
			<div class="center">
				<button type="submit" class="btn btn-success">Xác nhận</button>
			</div>
		</form>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<script type="text/javascript">
  function checkRegis(){
    var x = document.forms["regis"]['name'].value;
    var y1 = document.forms["regis"]['password'].value;
    var y2 = document.forms["regis"]['password_confirmation'].value;
    var z = document.forms["regis"]['account'].value;
    if (x == "") {
      alert("Bạn chưa nhập tên hiển thị");
      return false;
    }
    else if (z == "") {
      alert("Bạn chưa nhập tên tài khoản");
      return false;
    }
    else if (y1 == "") {
      alert("Bạn chưa nhập tên tài khoản");
      return false;
    }
    else if (y1 != y2) {
      alert("Mật khẩu nhập lại không khớp");
      return false;
    }
  }
  $("#frontID").change(function(){
            // var fullPath = $("#frontID").get(0).files;
            // var length = parseInt(fullPath.length);
            // if (length > 3) {alert("hệ thống chỉ cho phép up tối đa 3 file. hệ thống sẽ ghi nhận 3 file đầu của bạn"); length=3}
            // var string = '';
            // for(var i = 0;i<length;i++){
            //     var buf = event.target.files[i];
            //     const blob = new Blob( [buf] );
            //     string += "<img src='"+URL.createObjectURL(blob)+"'>"+"<br><label>"+fullPath.item(i).name+"</label>";
            // }
            // $("#frntid").html(string);
            var fullPath = document.getElementById('frontID').value;
            if (fullPath) {
              var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
              var filename = fullPath.substring(startIndex);
              if (filename.indexOf('\\') === 0 || filename.indexOf('/') === 0) {
                filename = filename.substring(1);
              }
              $("#ifid").attr("src",URL.createObjectURL(event.target.files[0]));
              $("#ifid").css("display","block");
              $("#fid").text(filename);
            }   
          });
  $("#backID").change(function(){
    var fullPath = document.getElementById('backID').value;
    if (fullPath) {
      var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
      var filename = fullPath.substring(startIndex);
      if (filename.indexOf('\\') === 0 || filename.indexOf('/') === 0) {
        filename = filename.substring(1);
      }
      $("#ibid").attr("src",URL.createObjectURL(event.target.files[0]));
      $("#ibid").css("display","block");
      $("#bid").text(filename);
    }   
  });
</script>

app/views/users/login.html.erb
<<<<<<< HEAD
<%= stylesheet_link_tag 'style1'%>
=======
>>>>>>> upstream/master
<section class="sign-in">
	<div class="container">
		<div class="signin-content">
			<div class="signin-image">
				<figure><%= image_tag("signup-image.jpg")%></figure>
				<%= link_to "Đăng ký tài khoản", new_user_path %>
			</div>
			<div class="signin-form">
				<h2 class="form-title">Đăng nhập</h2>
				<%= form_tag({},{:class => 'register-form',:name => "login", :onsubmit => "return checkLogin();"}) do %>
				<div class="form-group">
					<label class="lb" for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
					<%= text_field_tag :account,"",id:"pass",placeholder:"Tên đăng nhập"%>
				</div>
				<div class="form-group">
					<label class="lb" for="your_pass"><i class="zmdi zmdi-lock"></i></label>
					<%= password_field_tag :password,"",id:"pass",placeholder:"Mật khẩu"%>
				</div>
				<div class="form-group">
					<input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
					<label for="remember-me" class="label-agree-term"><span><span></span></span>Ghi nhớ đăng nhập</label>
				</div>
				<div class="form-group">
					<a href="?controller=misspass">Quên mật khẩu</a>
				</div>
				<div class="form-group form-button">
					<%= submit_tag "Đăng nhập",class:"form-submit" %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
	function checkLogin(){
		var x = document.forms["login"]['account'].value;
		var y = document.forms["login"]['password'].value;
		if (x == "") {
			alert("Bạn chưa nhập tên đăng nhập");
			return false;
		}
		else if (y == "") {
			alert("Bạn chưa nhập mật khẩu");
			return false;
		}
	}
</script>

app/views/users/new.html.erb
<<<<<<< HEAD
 <%= stylesheet_link_tag 'style1'%>

=======
>>>>>>> upstream/master
<div class="main">
	<section class="signup">
		<div class="container">
			<div class="signup-content">
				<div class="signup-form">
					<h2 class="form-title">Đăng ký tài khoản</h2>
					<%= render 'form', user: @user %>
				</div>
				<div class="signup-image"> 
					<figure><%= image_tag("signup-image.jpg")%></figure>
					<%= link_to "Tôi đã có tài khoản", user_login_path %>
				</div>
			</div>
		</div>
	</section>
</div>