config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  
=======
>>>>>>> upstream/master
  root "posts#index"

  resources :posts
  resources :users

<<<<<<< HEAD
  namespace :admin do 
    resources :posts
    resources :users
    resources :categories
    root to: "posts#index"
  end
  
  get '/user/login', to: 'users#login'
=======
>>>>>>> upstream/master
  get '/user/login', to: 'users#login'
  post '/user/login', to: 'users#login'
  get '/user/logout', to: 'users#logout'
  post '/users/new', to: 'users#create'
<<<<<<< HEAD
  post '/users/:id', to: 'users#topup'
=======
>>>>>>> upstream/master

  post 'posts/:id', to: 'bills#create'

  get 'posts/ajax/category_selection', to: 'posts#category_selection'
  get 'posts/ajax/province_selection', to: 'posts#province_selection'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
 	has_many :brands
<<<<<<< HEAD
 	has_many :posts
=======
>>>>>>> upstream/master

  	validates :brand, presence: true
end

app/controllers/admin/categories_controller.rb
<<<<<<< HEAD
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /Categories or /Categories.json
  def index
    @categories = Category.all
    @brands = Brand.all
  end

  # GET /Categories/1 or /Categories/1.json
  def show
  end

  # GET /Categories/new
  def new
    @category = Category.new
    @brand = Brand.new
    @categories = Category.all
  end

  # GET /Categories/1/edit
  def edit
  end

  # POST /Categories or /Categories.json
  def create
    @brand = Brand.new()
    @category = Category.new(category_params)
    respond_to do |format|
      if params[:typecategory] == "category"
        if @category.save
          format.html { redirect_to @category, notice: "category was successfully created." }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      else
        @brand[:name] = @category.name
        if @brand.save
          format.html { redirect_to @category, notice: "category was successfully created." }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /Categories/1 or /Categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Categories/1 or /Categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to Categories_url, notice: "category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    
end
=======
class Admin::BrandsController < ActionController::Base
	helper_method  :current_user

  def index
    @users = User.all
  end

end
>>>>>>> upstream/master

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/categories/_form.html.erb
<style type="text/css">
    #category{
        display: none;
    }
</style>
<div class="content-wrapper" style="min-height: 353px;">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thêm danh mục</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">danh mục</a></li>
                        <li class="breadcrumb-item active">Admin</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
              <%= form_with url: "/admin/categories", method: :post do |form| %>
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên danh mục</label>
                        <input type="text" name="category[name]" class="form-control" placeholder="Tên danh mục" >
                    </div>
                    <div class="form-group" id="category">
                        <label>Loại xe</label> <br>
                        <select class="form-control" >
                        <% @categories.each do |category|%>
                            <option value="<%= category.id %>"><%=category.name %></option>
                        <% end -%>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>danh mục nhỏ</label>
                        <input type="radio" name="typecategory" value="sub_category">
                        <label>danh mục lớn</label>
                        <input type="radio" name="typecategory" value="category" checked="checked">
                    </div>
                    <button type="submit"  class="btn btn-primary">Thêm</button>
                </div>
            <% end %>
        </div>
    </section>
</div>
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('input[type=radio][name=typecategory]').change(function () {
            if ($("input[name='typecategory']:checked").val() == 'sub_category') {
                document.getElementById('category').style.display = "block";
            }
            else if ($("input[name='typecategory']:checked").val() == 'category') {
                document.getElementById('category').style.display = "none";
            }
        });
    });
</script>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/admin/categories/index.html.erb
<div class="content-wrapper" style="min-height: 1203.6px;">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Danh sách danh mục</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Danh sách danh mục</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content-header">
            <div class="col-sm-2">
                <label>loại</label>
                <select id="change">
                    <option value="parent" selected>Loại xe</option>
                    <option value="sub">hãng xe</option>
                </select>
            </div>
    </section>
    <section>
        <div class="col-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12 col-md-6"></div>
                            <div class="col-sm-12 col-md-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Tên danh mục</th>
                                            <th style="text-align: center;" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Sửa</th>
                                            <th style="text-align: center;" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Xóa</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody id="category">
                                        <% stt = 0 %>
                                        <% type = 'sub' %>
                                        <% @categories.each do |category| %>
                                                <tr role="row" class="odd">
                                                    <td class="sorting_1"><%= stt+=1 %></td>
                                                    <td><%=category.name%></td>
                                                    <td style="text-align: center;">
                                                        <span class="badge bg-primary">
                                                            <a href="?controller=updateCategory&id=<%=category.id%>&type=<%=type%>">
                                                                <ion-icon name="create-outline"></ion-icon>
                                                            </a>
                                                        </span>
                                                    </td>
                                                    <td style="text-align: center;">
                                                        <span class="badge bg-danger">
                                                            <a href="javascript:;" data-id="<%=category.id%>" data-type="<%=type%>" id="del">
                                                                <ion-icon name="trash-outline"></ion-icon>
                                                            </a>
                                                        </span>
                                                    </td>
                                                </tr>
                                       <% end -%>
                                    </tbody>
                                   
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $("#change").change(function(){
            var type = $(this).val();
            var category = '';
            if(type == 'sub'){
                <%
                  type = 'sub';
                  stt = 0;
                  @brands.each do |category|
                %>
                category += '<tr role="row" class="odd">'+
                        '<td class="sorting_1"><%= stt+=1 %></td>'+
                        "<td><%=category.name%></td>"+
                        '<td style="text-align: center;">'+
                            '<span class="badge bg-primary">'+
                                '<a href="?controller=updateCategory&id=<%=category.id%>&type=<%=type%>">'+
                                    '<ion-icon name="create-outline"></ion-icon>'+
                                '</a>'+
                            '</span>'+
                        '</td>'+
                        '<td style="text-align: center;">'+
                            '<span class="badge bg-danger">'+
                                '<a href="javascript:;" data-id="<%=category.id%>" data-type="<%=type%>" id="del">'+
                                    '<ion-icon name="trash-outline"></ion-icon>'+
                                '</a>'+
                            '</span>'+
                        '</td>'+
                    '</tr>';
                <% end -%>
            }
            else if(type == 'parent'){
                <%
                    type = 'parent';
                    stt = 0;
                    @categories.each do |category|
                %>
                category += '<tr role="row" class="odd">'+
                        '<td class="sorting_1"><%=stt+=1%></td>'+
                        "<td><%=category.name%></td>"+
                        '<td style="text-align: center;">'+
                            '<span class="badge bg-primary">'+
                                '<a href="?controller=updateCategory&id=<%=category.id%>&type=<%=type%>">'+
                                    '<ion-icon name="create-outline"></ion-icon>'+
                                '</a>'+
                            '</span>'+
                        '</td>'+
                        '<td style="text-align: center;">'+
                            '<span class="badge bg-danger">'+
                                '<a href="javascript:;" data-id="<%=category.id%>" data-type="<%=type%>" id="del">'+
                                    '<ion-icon name="trash-outline"></ion-icon>'+
                                '</a>'+
                            '</span>'+
                        '</td>'+
                    '</tr>';
                <% end -%>
            }
            document.getElementById("category").innerHTML = category;
        });
        
     });
    $(document).on('click','#del',function(){
            var id = $(this).attr('data-id');
            var type =  $(this).attr('data-type');
            $.ajax({
                url: '?controller=delCategory',
                method:"POST",
                cache: false,
                data:{id:id, type:type},
                success:function(data){
                (this).closest('tr').remove();
                }
            });
        });
</script>

app/views/admin/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>