config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  
=======
>>>>>>> upstream/master
  root "posts#index"

  resources :posts
  resources :users

<<<<<<< HEAD
  namespace :admin do 
    resources :posts
    resources :users
    resources :categories
    root to: "posts#index"
  end
  
  get '/user/login', to: 'users#login'
=======
>>>>>>> upstream/master
  get '/user/login', to: 'users#login'
  post '/user/login', to: 'users#login'
  get '/user/logout', to: 'users#logout'
  post '/users/new', to: 'users#create'
<<<<<<< HEAD
  post '/users/:id', to: 'users#topup'
=======
>>>>>>> upstream/master

  post 'posts/:id', to: 'bills#create'

  get 'posts/ajax/category_selection', to: 'posts#category_selection'
  get 'posts/ajax/province_selection', to: 'posts#province_selection'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
		<style type="text/css">
			.py-lg{
				padding-top: 3rem;
				padding-bottom: 3rem;
			}
			ul{ list-style-type: none;
				padding: 0;
			}
			li{padding-bottom: 15px;}
			h3{
				color: #3C3241;
			}
		</style>
		<footer class="bg-black" style="margin-top: 20px; ">
			<div class="container py-lg">
				<div class="row footer-top-w3layouts">
					<div class="col-lg-4">
						<a class="navbar-brand col-2" href="#" > <%= image_tag("logo.png", style:"margin-left: auto;margin-right: auto;display: block; width: 80px; height: 80px")%></a>
							<ul class="footer-social text-left mt-lg-4 mt-3">
								<li class="mx-2">
									<i class="fas fa-map-marker-alt"></i>  71 Ngũ Hành Sơn - Đà Nẵng
								</li>
								<li class="mx-2">
									<i class="fas fa-phone"></i>   Phone: 0911989475
								</li>
								<li class="mx-2">
									<i class="fas fa-envelope"></i> Email: rent2000k@gmail.com

								</li>
							</ul>
					</div>
					<div class="col-lg-4 footer-grid-w3ls">
						<div class="footer-title">
							<h3>Chính sách</h3>
						</div>
						<ul class="footer-social text-left mt-lg-4 mt-3">
								<p>Chính sách 1</p>
								<p>Chính sách 2</p>
								<p>Chính sách 3</p>
								<p>Chính sách 4</p>
							</ul>
					</div>
					<div class="col-lg-4 footer-grid-w3ls">
						<div class="footer-title">
							<h3>Hỗ trợ</h3>
						</div>
						<div class="row">
							<ul class="col">
								<li>giới thiệu</li>
								<li>bảng giá</li>
								<li>bảng giá dịch vụ</li>
							</ul>
							<ul class="col">
								<li>quy chế hoạt động</li>
								<li>tiêu chuẩn duyệt tin</li>
								<li>thông tin ví rao vặt</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- //footer -->

app/views/layouts/_header.html.erb
<script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
<header class="bg-black">
  <div class="container">
   <nav class="navbar navbar-expand-lg row black  " >
    <a class="navbar-brand col-1" href="../">
      <%= image_tag("logo.png", style:"width: 80px; height: 80px")%>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="col-1"></div>
    <form class="form-inline my-2 my-lg-0 col-6" method="GET">
<<<<<<< HEAD
      <input class="form-control" type="search" name="search" placeholder="Search" aria-label="Search">
=======
      <input class="form-control" type="search" name="find" placeholder="Search" aria-label="Search">
>>>>>>> upstream/master
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="col-1"></div>
    <span class="navbar-text black col-3">
      <% if current_user %>
<<<<<<< HEAD
=======
        <% if current_user.role == 'admin' %> 
        <a href="View/admin" style="color: #28a745"><%=current_user.name%></a> |<%= link_to 'Đăng xuất', user_logout_path %> 
        <% else %>
>>>>>>> upstream/master
     <div class="dropdown" >
      <div class="dropbtn" style="color: #28a745"><%=current_user.name%></div>
      <div class="dropdown-content">
        <%= link_to 'Thông tin cá nhân', current_user  %> 
<<<<<<< HEAD
        <% if current_user.role == 'admin' %> 
        <%= link_to 'Admin', admin_root_path %> 
        <% else %>
        <%= link_to 'Đăng tin', new_post_path %>

       <% end %>
        <%= link_to 'Đăng xuất', user_logout_path %> 
      </div>
    </div>
    <% else %><%= link_to 'Đăng nhập', user_login_path %> 
    <% end %> 
=======
        <a href="?controller=profile&type=manage">Quản lý tin đăng</a>
        <%= link_to 'Đăng xuất', user_logout_path %> 
      </div>
    </div>
       <% end %>
    <% else %><%= link_to 'Đăng nhập', user_login_path %> 
    <% end %> |
    <%= link_to 'Đăng tin', new_post_path %>
>>>>>>> upstream/master
  </span>
</nav>
</div>
</header>
<section class="sticky">
  <div class="container">
    <div class="sticky" id="sticky" >
      <div class="area-inner">
        <div class="area-content">
          <div class="list-menu">
<<<<<<< HEAD
            <% categories.each do |category|%>
            <h2 class="item-menu">
              <%=link_to category.name, posts_path(category: category.name) %>
            </h2>
            <% end -%>
=======
            <h2 class="item-menu">
              <a href="?controller=home&type=4">
                <span >xe điện</span>
              </a>
            </h2>
            <h2 class="item-menu">
              <a href="?controller=home&type=1">xe máy</a>
            </h2>
            <h2 class="item-menu">
              <a class="menu-link" href="?controller=home&type=2">
                <span>xe 4 chỗ</span>
              </a>
            </h2>
            <h2 class="item-menu">
              <a href="?controller=home&type=3">xe 7 chỗ</a>
            </h2>
            <h2 class="item-menu">
              <a href="?controller=home&type=5">xe du lịch</a>
            </h2>
>>>>>>> upstream/master
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% if current_page?('/') %>
  <div class="container">
    <%= image_tag("banner.png", class:"banner")%>
  </div>
<% end %>
<script type="text/javascript">
  window.onscroll = function(){
    var x = $(window).scrollTop();
    if(x>115){
     $('.sticky').css({                   
      position: 'sticky',
    });
   }
   else  $('.sticky').css({                   
    position: 'static',
  });
 }
 function ask(){
  if (confirm("Bản phải đăng nhập để thực hiện thao tác này")) window.location.href = "?controller=signin";
}
</script>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'ionicons.min'%>
    <%= stylesheet_link_tag 'tempusdominus-bootstrap-4.min'%>
    <%= stylesheet_link_tag 'jqvmap.min'%>
    <%= stylesheet_link_tag 'adminlte.min'%>
    <%= stylesheet_link_tag 'icheck-bootstrap.min'%>
    <%= stylesheet_link_tag 'OverlayScrollbars.min'%>
    <%= stylesheet_link_tag 'daterangepicker'%>
    <%= stylesheet_link_tag 'summernote-bs4'%>
    <%= stylesheet_link_tag 'font'%>
    <%= javascript_pack_tag 'adminlte' %>
    
  </head>
  <body>
    <%=render "admin/layouts/header"%>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
    <%=render "admin/layouts/footer"%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<<<<<<< HEAD
=======

>>>>>>> upstream/master
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap'%>
    <%= stylesheet_link_tag 'style'%>
<<<<<<< HEAD
=======
    <%= stylesheet_link_tag 'style1'%>
>>>>>>> upstream/master
    <%= javascript_pack_tag 'ckeditor' %>
    
  </head>
  <body>
    <%=render "layouts/header"%>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
<<<<<<< HEAD
=======
    <script type="text/javascript">
      
    </script>

>>>>>>> upstream/master
    <%= yield %>
    <%=render "layouts/footer"%>
  </body>
</html>